FROM golang:1.15 as build

RUN apt-get update && apt-get install -y ninja-build

RUN go get -u github.com/BohdanShmalko/Implementation-assembly-system/build/cmd/bood
RUN go get gopkg.in/check.v1

WORKDIR /go/src/practice-2
COPY . .

# TODO: Замініть на запуск bood, який призводить до виконання інтеграційних тестів.
ENTRYPOINT ["bood", "--integration-tests=true"]
