version: '2.1'

networks:
  servers:

services:

  balancer:
    build: .
    command: "lb"
    networks:
      - servers
    ports:
      - "8090:8090"

  server1:
    build: .
    networks:
      - servers
    ports:
      - "8081:8080"

  server2:
    build: .
    networks:
      - servers
    ports:
      - "8082:8080"

  server3:
    build: .
    networks:
      - servers
    ports:
      - "8083:8080"

  database:
    command: "db"
    build: .
    networks:
      - servers
    ports:
      - "8085:8085"
